base:
  random_state: 42
  test_size: 0.2
  target_column: Exited

data:
  raw_data_link: https://raw.githubusercontent.com/jslhost/dataset_repo/refs/heads/main/Churn_Modelling.csv
  raw_dataset_path: data/raw_dataset.csv
  clean_dataset_path: data/clean_dataset.csv
  preprocessed_features_path: data/preprocessed_features.npz
  columns_to_drop:
    - RowNumber
    - CustomerId

model:
  path: model.pkl
  # SVC parameters (example, can be expanded)
  # C: 1.0
  # kernel: rbf

reports:
  dir: reports
  classification_report_path: reports/classification-report.txt
  confusion_matrix_path: reports/confusion-matrix.png
