project:
  type: website

website:
  title: "ml-churn"
  site-url: https://jslhost.github.io/ml-pipeline-template/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include: true
